export enum ExceptionCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

  // tenant
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_ALREADY_EXISTS = 'TENANT_ALREADY_EXISTS',
  TENANT_ROOM_NOT_FOUND = 'TENANT_NOT',

  // building
  BUILDING_NOT_FOUND = 'BUILDING_NOT_FOUND',

  // lease
  LEASE_NOT_FOUND = 'LEASE_NOT_FOUND',
  LEASE_ALREADY_EXISTS = 'LEASE_ALREADY_EXISTS',

  // generic
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // meter
  METER_NOT_FOUND = 'METER_NOT_FOUND',
  METER_ALREADY_EXISTS = 'METER_ALREADY_EXISTS',

  // invoice
  INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND',

  // payment
  PAYMENT_EXCEEDS_INVOICE_TOTAL = 'PAYMENT_EXCEEDS_INVOICE_TOTAL',
}
