export const BUILDINGS = [
  {
    name: 'Stark Tower',
    owner: 'Tony Stark',
    manager: 'Pepper Potts',
    tenants: [
      'Steve Rogers',
      'Natasha Romanoff',
      'Bruce Banner',
      'Thor Odinson',
      'Clint Barton',
      'Wanda Maximoff',
      'Vision',
      'Peter Parker',
    ],
  },
  {
    name: 'Xavier Institute',
    owner: 'Charles Xavier',
    manager: 'Logan',
    tenants: ['Jean Grey', 'Cyclops', 'Storm', 'Beast', 'Rogue', 'Gambit'],
  },
  {
    name: 'Wayne Manor',
    owner: 'Bruce Wayne',
    manager: 'Alfred',
    tenants: [
      'Clark Kent',
      'Diana Prince',
      'Barry Allen',
      'Hal Jordan',
      'Arthur Curry',
    ],
  },
  {
    name: 'Daily Planet',
    owner: 'Perry White',
    manager: 'Lois Lane',
    tenants: ['Jimmy Olsen', 'Lex Luthor', 'Supergirl', 'Zatanna'],
  },
  {
    name: 'Going Merry Residency',
    owner: 'Monkey D. Luffy',
    manager: 'Nami',
    tenants: [
      'Roronoa Zoro',
      'Usopp',
      'Sanji',
      'Tony Tony Chopper',
      'Nico Robin',
      'Franky',
      'Brook',
      'Jinbe',
    ],
  },
  {
    name: 'Hidden Leaf Apartments',
    owner: 'Naruto Uzumaki',
    manager: 'Shikamaru',
    tenants: [
      'Sasuke Uchiha',
      'Sakura Haruno',
      'Kakashi Hatake',
      'Hinata Hyuga',
      'Rock Lee',
      'Neji Hyuga',
    ],
  },
  {
    name: 'Tokyo Jujutsu Dorms',
    owner: 'Satoru Gojo',
    manager: 'Nanami',
    tenants: [
      'Yuji Itadori',
      'Megumi Fushiguro',
      'Nobara Kugisaki',
      'Yuta Okkotsu',
      'Maki Zenin',
    ],
  },
];
